USE [PRI2015]
GO

INSERT INTO [dbo].[TDU_ArtigoIdioma]
           ([CDU_idArtigo]
           ,[CDU_idIdioma]
           ,[CDU_Tipo])
     VALUES
			('Grand Theft Auto V (PS3)', 3, 'Voz'),
			('Grand Theft Auto V (PS3)', 2, 'Subtitulo'),
			('Grand Theft Auto V (PS3)', 3, 'Subtitulo'),
			('Grand Theft Auto V (PS3)', 4, 'Subtitulo'),
			('Grand Theft Auto V (PS3)', 5, 'Subtitulo'),
			('Grand Theft Auto V (PS3)', 6, 'Subtitulo'),

			('Grand Theft Auto V (PS4)', 3, 'Voz'),
			('Grand Theft Auto V (PS4)', 2, 'Subtitulo'),
			('Grand Theft Auto V (PS4)', 3, 'Subtitulo'),
			('Grand Theft Auto V (PS4)', 4, 'Subtitulo'),
			('Grand Theft Auto V (PS4)', 5, 'Subtitulo'),
			('Grand Theft Auto V (PS4)', 6, 'Subtitulo'),

			('Grand Theft Auto V (PC)', 3, 'Voz'),
			('Grand Theft Auto V (PC)', 2, 'Subtitulo'),
			('Grand Theft Auto V (PC)', 3, 'Subtitulo'),
			('Grand Theft Auto V (PC)', 4, 'Subtitulo'),
			('Grand Theft Auto V (PC)', 5, 'Subtitulo'),
			('Grand Theft Auto V (PC)', 6, 'Subtitulo'),

			('Grand Theft Auto V (X360)', 3, 'Voz'),
			('Grand Theft Auto V (X360)', 2, 'Subtitulo'),
			('Grand Theft Auto V (X360)', 3, 'Subtitulo'),
			('Grand Theft Auto V (X360)', 4, 'Subtitulo'),
			('Grand Theft Auto V (X360)', 5, 'Subtitulo'),
			('Grand Theft Auto V (X360)', 6, 'Subtitulo'),

			('Grand Theft Auto V (XOne)', 3, 'Voz'),
			('Grand Theft Auto V (XOne)', 2, 'Subtitulo'),
			('Grand Theft Auto V (XOne)', 3, 'Subtitulo'),
			('Grand Theft Auto V (XOne)', 4, 'Subtitulo'),
			('Grand Theft Auto V (XOne)', 5, 'Subtitulo'),
			('Grand Theft Auto V (XOne)', 6, 'Subtitulo'),

			('Final Fantasy XIV: A Realm Reborn (PS3)', 9, 'Voz'),
			('Final Fantasy XIV: A Realm Reborn (PS3)', 3, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (PS3)', 6, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (PS3)', 9, 'Subtitulo'),

			('Final Fantasy XIV: A Realm Reborn (PS4)', 9, 'Voz'),
			('Final Fantasy XIV: A Realm Reborn (PS4)', 3, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (PS4)', 6, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (PS4)', 9, 'Subtitulo'),

			('Final Fantasy XIV: A Realm Reborn (PC)', 9, 'Voz'),
			('Final Fantasy XIV: A Realm Reborn (PC)', 3, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (PC)', 6, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (PC)', 9, 'Subtitulo'),

			('Final Fantasy XIV: A Realm Reborn (X360)', 9, 'Voz'),
			('Final Fantasy XIV: A Realm Reborn (X360)', 3, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (X360)', 6, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (X360)', 9, 'Subtitulo'),

			('Final Fantasy XIV: A Realm Reborn (XOne)', 9, 'Voz'),
			('Final Fantasy XIV: A Realm Reborn (XOne)', 3, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (XOne)', 6, 'Subtitulo'),
			('Final Fantasy XIV: A Realm Reborn (XOne)', 9, 'Subtitulo'),

			('Minecraft (PS3)', 1, 'Subtitulo'),
			('Minecraft (PS3)', 2, 'Subtitulo'),
			('Minecraft (PS3)', 3, 'Subtitulo'),
			('Minecraft (PS3)', 4, 'Subtitulo'),
			('Minecraft (PS3)', 5, 'Subtitulo'),
			('Minecraft (PS3)', 6, 'Subtitulo'),
			('Minecraft (PS3)', 7, 'Subtitulo'),
			('Minecraft (PS3)', 8, 'Subtitulo'),
			('Minecraft (PS3)', 9, 'Subtitulo'),

			('Minecraft (PS4)', 1, 'Subtitulo'),
			('Minecraft (PS4)', 2, 'Subtitulo'),
			('Minecraft (PS4)', 3, 'Subtitulo'),
			('Minecraft (PS4)', 4, 'Subtitulo'),
			('Minecraft (PS4)', 5, 'Subtitulo'),
			('Minecraft (PS4)', 6, 'Subtitulo'),
			('Minecraft (PS4)', 7, 'Subtitulo'),
			('Minecraft (PS4)', 8, 'Subtitulo'),
			('Minecraft (PS4)', 9, 'Subtitulo'),

			('Minecraft (PSP)', 1, 'Subtitulo'),
			('Minecraft (PSP)', 2, 'Subtitulo'),
			('Minecraft (PSP)', 3, 'Subtitulo'),
			('Minecraft (PSP)', 4, 'Subtitulo'),
			('Minecraft (PSP)', 5, 'Subtitulo'),
			('Minecraft (PSP)', 6, 'Subtitulo'),
			('Minecraft (PSP)', 7, 'Subtitulo'),
			('Minecraft (PSP)', 8, 'Subtitulo'),
			('Minecraft (PSP)', 9, 'Subtitulo'),

			('Minecraft (PSV)', 1, 'Subtitulo'),
			('Minecraft (PSV)', 2, 'Subtitulo'),
			('Minecraft (PSV)', 3, 'Subtitulo'),
			('Minecraft (PSV)', 4, 'Subtitulo'),
			('Minecraft (PSV)', 5, 'Subtitulo'),
			('Minecraft (PSV)', 6, 'Subtitulo'),
			('Minecraft (PSV)', 7, 'Subtitulo'),
			('Minecraft (PSV)', 8, 'Subtitulo'),
			('Minecraft (PSV)', 9, 'Subtitulo'),

			('Minecraft (PC)', 1, 'Subtitulo'),
			('Minecraft (PC)', 2, 'Subtitulo'),
			('Minecraft (PC)', 3, 'Subtitulo'),
			('Minecraft (PC)', 4, 'Subtitulo'),
			('Minecraft (PC)', 5, 'Subtitulo'),
			('Minecraft (PC)', 6, 'Subtitulo'),
			('Minecraft (PC)', 7, 'Subtitulo'),
			('Minecraft (PC)', 8, 'Subtitulo'),
			('Minecraft (PC)', 9, 'Subtitulo'),

			('Minecraft (X360)', 1, 'Subtitulo'),
			('Minecraft (X360)', 2, 'Subtitulo'),
			('Minecraft (X360)', 3, 'Subtitulo'),
			('Minecraft (X360)', 4, 'Subtitulo'),
			('Minecraft (X360)', 5, 'Subtitulo'),
			('Minecraft (X360)', 6, 'Subtitulo'),
			('Minecraft (X360)', 7, 'Subtitulo'),
			('Minecraft (X360)', 8, 'Subtitulo'),
			('Minecraft (X360)', 9, 'Subtitulo'),

			('Minecraft (XOne)', 1, 'Subtitulo'),
			('Minecraft (XOne)', 2, 'Subtitulo'),
			('Minecraft (XOne)', 3, 'Subtitulo'),
			('Minecraft (XOne)', 4, 'Subtitulo'),
			('Minecraft (XOne)', 5, 'Subtitulo'),
			('Minecraft (XOne)', 6, 'Subtitulo'),
			('Minecraft (XOne)', 7, 'Subtitulo'),
			('Minecraft (XOne)', 8, 'Subtitulo'),
			('Minecraft (XOne)', 9, 'Subtitulo'),

			('Assassin''s Creed: Unity (PS3)', 1, 'Voz'),
			('Assassin''s Creed: Unity (PS3)', 2, 'Voz'),
			('Assassin''s Creed: Unity (PS3)', 3, 'Voz'),
			('Assassin''s Creed: Unity (PS3)', 4, 'Voz'),
			('Assassin''s Creed: Unity (PS3)', 5, 'Voz'),
			('Assassin''s Creed: Unity (PS3)', 6, 'Voz'),
			('Assassin''s Creed: Unity (PS3)', 1, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS3)', 2, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS3)', 3, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS3)', 4, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS3)', 5, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS3)', 6, 'Subtitulo'),

			('Assassin''s Creed: Unity (PS4)', 1, 'Voz'),
			('Assassin''s Creed: Unity (PS4)', 2, 'Voz'),
			('Assassin''s Creed: Unity (PS4)', 3, 'Voz'),
			('Assassin''s Creed: Unity (PS4)', 4, 'Voz'),
			('Assassin''s Creed: Unity (PS4)', 5, 'Voz'),
			('Assassin''s Creed: Unity (PS4)', 6, 'Voz'),
			('Assassin''s Creed: Unity (PS4)', 1, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS4)', 2, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS4)', 3, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS4)', 4, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS4)', 5, 'Subtitulo'),
			('Assassin''s Creed: Unity (PS4)', 6, 'Subtitulo'),

			('Assassin''s Creed: Unity (X360)', 1, 'Voz'),
			('Assassin''s Creed: Unity (X360)', 2, 'Voz'),
			('Assassin''s Creed: Unity (X360)', 3, 'Voz'),
			('Assassin''s Creed: Unity (X360)', 4, 'Voz'),
			('Assassin''s Creed: Unity (X360)', 5, 'Voz'),
			('Assassin''s Creed: Unity (X360)', 6, 'Voz'),
			('Assassin''s Creed: Unity (X360)', 1, 'Subtitulo'),
			('Assassin''s Creed: Unity (X360)', 2, 'Subtitulo'),
			('Assassin''s Creed: Unity (X360)', 3, 'Subtitulo'),
			('Assassin''s Creed: Unity (X360)', 4, 'Subtitulo'),
			('Assassin''s Creed: Unity (X360)', 5, 'Subtitulo'),
			('Assassin''s Creed: Unity (X360)', 6, 'Subtitulo'),

			('Assassin''s Creed: Unity (XOne)', 1, 'Voz'),
			('Assassin''s Creed: Unity (XOne)', 2, 'Voz'),
			('Assassin''s Creed: Unity (XOne)', 3, 'Voz'),
			('Assassin''s Creed: Unity (XOne)', 4, 'Voz'),
			('Assassin''s Creed: Unity (XOne)', 5, 'Voz'),
			('Assassin''s Creed: Unity (XOne)', 6, 'Voz'),
			('Assassin''s Creed: Unity (XOne)', 1, 'Subtitulo'),
			('Assassin''s Creed: Unity (XOne)', 2, 'Subtitulo'),
			('Assassin''s Creed: Unity (XOne)', 3, 'Subtitulo'),
			('Assassin''s Creed: Unity (XOne)', 4, 'Subtitulo'),
			('Assassin''s Creed: Unity (XOne)', 5, 'Subtitulo'),
			('Assassin''s Creed: Unity (XOne)', 6, 'Subtitulo'),

			('Call of Duty: Advanced Warfare (PS3)', 3, 'Voz'),
			('Call of Duty: Advanced Warfare (PS3)', 7, 'Voz'),
			('Call of Duty: Advanced Warfare (PS3)', 3, 'Subtitulo'),

			('Call of Duty: Advanced Warfare (PS4)', 3, 'Voz'),
			('Call of Duty: Advanced Warfare (PS4)', 7, 'Voz'),
			('Call of Duty: Advanced Warfare (PS4)', 3, 'Subtitulo'),

			('Call of Duty: Advanced Warfare (PC)', 3, 'Voz'),
			('Call of Duty: Advanced Warfare (PC)', 7, 'Voz'),
			('Call of Duty: Advanced Warfare (PC)', 3, 'Subtitulo'),

			('Call of Duty: Advanced Warfare (X360)', 3, 'Voz'),
			('Call of Duty: Advanced Warfare (X360)', 7, 'Voz'),
			('Call of Duty: Advanced Warfare (X360)', 3, 'Subtitulo'),

			('Call of Duty: Advanced Warfare (XOne)', 3, 'Voz'),
			('Call of Duty: Advanced Warfare (XOne)', 7, 'Voz'),
			('Call of Duty: Advanced Warfare (XOne)', 3, 'Subtitulo'),

			('Tekken 6 (PS3)', 6, 'Voz'),
			('Tekken 6 (PS3)', 7, 'Subtitulo'),

			('Tekken 6 (PSP)', 6, 'Voz'),
			('Tekken 6 (PSP)', 7, 'Subtitulo'),

			('Pro Evolution Soccer 2016 (PS3)', 1, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 2, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 3, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 4, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 5, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 6, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 7, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 8, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 9, 'Voz'),
			('Pro Evolution Soccer 2016 (PS3)', 1, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS3)', 2, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS3)', 3, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS3)', 4, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS3)', 5, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS3)', 6, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS3)', 7, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS3)', 8, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS3)', 9, 'Subtitulo'),

			('Pro Evolution Soccer 2016 (PS4)', 1, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 2, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 3, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 4, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 5, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 6, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 7, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 8, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 9, 'Voz'),
			('Pro Evolution Soccer 2016 (PS4)', 1, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS4)', 2, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS4)', 3, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS4)', 4, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS4)', 5, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS4)', 6, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS4)', 7, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS4)', 8, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PS4)', 9, 'Subtitulo'),

			('Pro Evolution Soccer 2016 (PC)', 1, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 2, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 3, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 4, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 5, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 6, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 7, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 8, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 9, 'Voz'),
			('Pro Evolution Soccer 2016 (PC)', 1, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PC)', 2, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PC)', 3, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PC)', 4, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PC)', 5, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PC)', 6, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PC)', 7, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PC)', 8, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (PC)', 9, 'Subtitulo'),

			('Pro Evolution Soccer 2016 (X360)', 1, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 2, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 3, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 4, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 5, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 6, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 7, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 8, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 9, 'Voz'),
			('Pro Evolution Soccer 2016 (X360)', 1, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (X360)', 2, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (X360)', 3, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (X360)', 4, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (X360)', 5, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (X360)', 6, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (X360)', 7, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (X360)', 8, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (X360)', 9, 'Subtitulo'),

			('Pro Evolution Soccer 2016 (XOne)', 1, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 2, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 3, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 4, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 5, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 6, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 7, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 8, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 9, 'Voz'),
			('Pro Evolution Soccer 2016 (XOne)', 1, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (XOne)', 2, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (XOne)', 3, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (XOne)', 4, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (XOne)', 5, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (XOne)', 6, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (XOne)', 7, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (XOne)', 8, 'Subtitulo'),
			('Pro Evolution Soccer 2016 (XOne)', 9, 'Subtitulo'),

			('Pokémon Omega Ruby (3DS)', 2, 'Subtitulo'),
			('Pokémon Omega Ruby (3DS)', 3, 'Subtitulo'),
			('Pokémon Omega Ruby (3DS)', 4, 'Subtitulo'),
			('Pokémon Omega Ruby (3DS)', 5, 'Subtitulo'),
			('Pokémon Omega Ruby (3DS)', 6, 'Subtitulo'),
			('Pokémon Omega Ruby (3DS)', 9, 'Subtitulo'),

			('Pokémon Alpha Sapphire (3DS)', 2, 'Subtitulo'),
			('Pokémon Alpha Sapphire (3DS)', 3, 'Subtitulo'),
			('Pokémon Alpha Sapphire (3DS)', 4, 'Subtitulo'),
			('Pokémon Alpha Sapphire (3DS)', 5, 'Subtitulo'),
			('Pokémon Alpha Sapphire (3DS)', 6, 'Subtitulo'),
			('Pokémon Alpha Sapphire (3DS)', 9, 'Subtitulo'),

			('The Legend of Zelda: Majora''s Mask 3D (3DS)', 2, 'Subtitulo'),
			('The Legend of Zelda: Majora''s Mask 3D (3DS)', 3, 'Subtitulo'),
			('The Legend of Zelda: Majora''s Mask 3D (3DS)', 4, 'Subtitulo'),
			('The Legend of Zelda: Majora''s Mask 3D (3DS)', 5, 'Subtitulo'),
			('The Legend of Zelda: Majora''s Mask 3D (3DS)', 6, 'Subtitulo'),
			('The Legend of Zelda: Majora''s Mask 3D (3DS)', 9, 'Subtitulo')
GO


