USE [PRI2015]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TDU_Genero](
	[CDU_ID] [int] NOT NULL,
	[CDU_Nome] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TDU_Genero] PRIMARY KEY CLUSTERED 
(
	[CDU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[TDU_Idioma](
	[CDU_ID] [int] NOT NULL,
	[CDU_Nome] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TDU_Idioma] PRIMARY KEY CLUSTERED 
(
	[CDU_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[TDU_ArtigoGenero](
	[CDU_idArtigo] [varchar](50) NOT NULL,
	[CDU_idGenero] [int] NOT NULL,
 CONSTRAINT [PK_TDU_ArtigoGenero] PRIMARY KEY CLUSTERED 
(
	[CDU_idArtigo] ASC,
	[CDU_idGenero] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[TDU_ArtigoIdioma](
	[CDU_idArtigo] [varchar](50) NOT NULL,
	[CDU_idIdioma] [int] NOT NULL,
	[CDU_Tipo] [varchar](50) NOT NULL,
 CONSTRAINT [PK_TDU_ArtigoIdioma] PRIMARY KEY CLUSTERED 
(
	[CDU_idArtigo] ASC,
	[CDU_idIdioma] ASC,
	[CDU_Tipo] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[TDU_Classificacao](
	[CDU_idArtigo] [varchar](50) NOT NULL,
	[CDU_idCliente] [varchar](50) NOT NULL,
	[CDU_Valor] [int] NOT NULL,
	[CDU_Comentario] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TDU_Classificacao] PRIMARY KEY CLUSTERED 
(
	[CDU_idArtigo] ASC,
	[CDU_idCliente] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[TDU_Pagamento](
	[CDU_idArtigo] [varchar](50) NOT NULL,
	[CDU_CodCliente] [varchar](50) NOT NULL,
	[CDU_adicionado] [datetime] NOT NULL,
	[CDU_comprado] [datetime] NULL,
 CONSTRAINT [PK_TDU_Pagamento] PRIMARY KEY CLUSTERED 
(
	[CDU_idArtigo] ASC,
	[CDU_CodCliente] ASC,
	[CDU_adicionado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO



SET ANSI_PADDING OFF
GO